let product = [
    {
        id: "1",
        image: "shoes/shoes1-1.webp",
        pics: "shoes/shoes1-1.webp,shoes/shoes1-2.webp,shoes/shoes1-3.webp,shoes/shoes1-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 1730,
        // priceincrease: 1730,
        oldPrice: 2500,
        discount: "20%",
        description: " Shoes Women's 2024 New Foreign Trade Women's Shoes Breathable Shoes Women's Cross-border Lace-up Fashion Trendy Sports Women's Shoes",
        rating: "⭐⭐⭐⭐"
    },
    {
        id: "2",
        image: "shoes/shoes2-1.webp",
        pics: "shoes/shoes2-1.webp,shoes/shoes2-2.webp,shoes/shoes2-3.webp,shoes/shoes2-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 3915,
        oldPrice: 5500,
        discount: "15%",
        description: "  Breathable Women's Slip-On Sneakers - Lightweight, Air Cushion Shock Absorption, Knit Upper,Casual Dance Shoes with Height Boost, All-Season Wear",
        rating: "⭐⭐⭐⭐⭐"
    },
    {
        id: "3",
        image: "shoes/shoes3-1.webp",
        pics: "shoes/shoes3-1.webp,shoes/shoes3-2.webp,shoes/shoes3-3.webp,shoes/shoes3-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 1930,
        oldPrice: 3900,
        discount: "20%",
        description: "  Women's Solid Color Knitted Sneakers, Lace Up Soft Sole Lightweight Walking Shoes, Low-top Breathable Running Shoes",
        rating: "⭐⭐⭐⭐⭐"
    },
    {
        id: "4",
        image: "shoes/shoes4-1.webp",
        pics: "shoes/shoes4-1.webp,shoes/shoes4-2.webp,shoes/shoes4-3.webp,shoes/shoes4-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 1570,
        oldPrice: 3267,
        discount: "50%",
        description: "Women's Breathable Camouflage Sports Sneakers, Low Top Lace-Up Fabric Shoes with EVA Sole and Rubber Patch, All-Season Plain Toe Design",
        rating: "⭐⭐⭐⭐"
    },
    {
        id: "5",
        image: "shoes/shoes5-1.webp",
        pics: "shoes/shoes5-1.webp,shoes/shoes5-2.webp,shoes/shoes5-3.webp,shoes/shoes5-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 2700,
        oldPrice: 6200,
        discount: "65%",
        description: " Shoes Women's 2024 New Foreign Trade Women's Shoes Breathable Shoes Women's Cross-border Lace-up Fashion Trendy Sports Women's Shoes",
        rating: "⭐⭐⭐⭐⭐"
    },
    {
        id: "6",
        image: "shoes/shoes6-1.webp",
        pics: "shoes/shoes6-1.webp,shoes/shoes6-2.webp,shoes/shoes6-3.webp,shoes/shoes6-4.webp",
        category: "Women's slippers",
        title: "slippers",
        price: 945,
        oldPrice: 1200,
        discount: "25%",
        description: " Women's Comfy EVA Slides - Thick Sole, Non-Slip, Casual Slip-On Slippers in Pink, Green, Brown with Ribbed Texture - Perfect for Indoor/Outdoor Use, Beach & Home Relaxation, Ladies Slippers",
        rating: "⭐⭐⭐⭐"
    },
    {
        id: "7",
        image: "shoes/shoes7-1.webp",
        pics: "shoes/shoes7-1.webp,shoes/shoes7-2.webp,shoes/shoes7-3.webp,shoes/shoes7-4.webp",
        category: "Women's slippers",
        title: "slippers",
        price: 1024,
        oldPrice: 3564,
        discount: "75%",
        description: " Elegant Floral Linen Slippers for Women - Soft, Non-Slip Sole, Breathable Indoor Shoes with Cross Design, Perfect for All Seasons, Elegant Style",
        rating: "⭐⭐⭐⭐"
    },
    {
        id: "8",
        image: "shoes/shoes8-1.webp",
        pics: "shoes/shoes8-1.webp,shoes/shoes8-2.webp,shoes/shoes8-3.webp,shoes/shoes8-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 1829,
        oldPrice: 6790,
        discount: "85%",
        description: " Women's Casual Slip-On Sneakers - Solid Color, Soft Fabric Lining, Non-Slip PU Sole for Fall",
        rating: "⭐⭐⭐⭐⭐"
    },
    {
        id: "9",
        image: "shoes/shoes9-1.webp",
        pics: "shoes/shoes9-1.webp,shoes/shoes9-2.webp,shoes/shoes9-3.webp,shoes/shoes9-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers",
        price: 1942,
        oldPrice: 11554,
        discount: "90%",
        description: " Women's Fashion Lightweight Sneakers, Breathable Mesh Lace Up Outdoor Shoes, Casual Comfortable Walking Shoes For Daily Wear",
        rating: "⭐⭐⭐⭐⭐"
    },
    {
        id: "10",
        image: "shoes/shoes10-1.webp",
        pics: "shoes/shoes10-1.webp,shoes/shoes10-2.webp,shoes/shoes10-3.webp,shoes/shoes10-4.webp",
        category: "Women's Flats",
        title: "Flats",
        price: 3172,
        oldPrice: 10891,
        discount: "35%",
        description: "Chic Women's Ballet Flats with Bowknot - Comfortable Slip-On Shoes, Soft Sole, Versatile for All Seasons",
        rating: "⭐⭐⭐⭐"
    },
]