let product = [
    {
        id: "1",
        image: "shoes/shoes1-1.webp",
        pics: "shoes/shoes1-1.webp,shoes/shoes1-2.webp,shoes/shoes1-3.webp,shoes/shoes1-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1730,
        oldPrice: 2500,
        discount: "-20%",
        description: " Shoes Women's 2024 New Foreign Trade Women's Shoes Breathable Shoes Women's Cross-border Lace-up Fashion Trendy Sports Women's Shoes",
        rating: "4.4 ⭐⭐⭐⭐",
        sold: "5k +",
        sizes: ["4", "4.5", "5", "6", "6.5", "7", "7.5", "8",],
        colors: ["redOrange", "LightBrown", "NavyBlue", "Grey"]
    },
    {
        id: "2",
        image: "shoes/shoes2-1.webp",
        pics: "shoes/shoes2-1.webp,shoes/shoes2-2.webp,shoes/shoes2-3.webp,shoes/shoes2-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 3915,
        oldPrice: 5500,
        discount: "-15%",
        description: "Breathable Women's Slip-On Sneakers - Lightweight, Air Cushion Shock Absorption, Knit Upper,Casual Dance Shoes with Height Boost, All-Season Wear",
        rating: "4.8 ⭐⭐⭐⭐⭐",
        sold: "2k +",
        sizes: ["4", "5", "6.5", "7", "8",],
        colors: ["Black", "Grey", "Purple", "Black&White"]
    },
    {
        id: "3",
        image: "shoes/shoes3-1.webp",
        pics: "shoes/shoes3-1.webp,shoes/shoes3-2.webp,shoes/shoes3-3.webp,shoes/shoes3-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1930,
        oldPrice: 3900,
        discount: "-20%",
        description: "  Women's Solid Color Knitted Sneakers, Lace Up Soft Sole Lightweight Walking Shoes, Low-top Breathable Running Shoes",
        rating: "4.9 ⭐⭐⭐⭐⭐",
        sold: "19k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7", "7.5", "8",],
        colors: ["Black", "Red", "Pink", "White"]
    },
    {
        id: "4",
        image: "shoes/shoes4-1.webp",
        pics: "shoes/shoes4-1.webp,shoes/shoes4-2.webp,shoes/shoes4-3.webp,shoes/shoes4-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1570,
        oldPrice: 3267,
        discount: "-50%",
        description: "Women's Breathable Camouflage Sports Sneakers, Low Top Lace-Up Fabric Shoes with EVA Sole and Rubber Patch, All-Season Plain Toe Design",
        rating: "4.6 ⭐⭐⭐⭐",
        sold: "15k +",
        sizes: ["3.5", "4.5", "6.5", "7.5",],
        colors: ["Pink", "Blue", "Brown", "Black"]
    },
    {
        id: "5",
        image: "shoes/shoes5-1.webp",
        pics: "shoes/shoes5-1.webp,shoes/shoes5-2.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 2700,
        oldPrice: 6200,
        discount: "-65%",
        description: " Shoes Women's 2024 New Foreign Trade Women's Shoes Breathable Shoes Women's Cross-border Lace-up Fashion Trendy Sports Women's Shoes",
        rating: "4.8 ⭐⭐⭐⭐⭐",
        sold: "35k +",
        sizes: ["3.5", "4", "4.5", "5", "6",],
        colors: ["White", "Grey"]
    },
    {
        id: "6",
        image: "shoes/shoes6-1.webp",
        pics: "shoes/shoes6-1.webp,shoes/shoes6-2.webp,shoes/shoes6-3.webp,shoes/shoes6-4.webp",
        category: "Women's slippers",
        title: "slippers ",
        price: 945,
        oldPrice: 1200,
        discount: "-25%",
        description: " Women's Comfy EVA Slides - Thick Sole, Non-Slip, Casual Slip-On Slippers in Pink, Green, Brown with Ribbed Texture - Perfect for Indoor/Outdoor Use, Beach & Home Relaxation, Ladies Slippers",
        rating: "3.9 ⭐⭐⭐⭐",
        sold: "11k + ",
        sizes: ["6.5", "7", "7.5", "8",],
        colors: ["Pink", "Khaki", "Grey", "White"]
    },
    {
        id: "7",
        image: "shoes/shoes7-1.webp",
        pics: "shoes/shoes7-1.webp,shoes/shoes7-2.webp,shoes/shoes7-3.webp,shoes/shoes7-4.webp",
        category: "Women's slippers",
        title: "slippers ",
        price: 1024,
        oldPrice: 3564,
        discount: "-75%",
        description: " Elegant Floral Linen Slippers for Women - Soft, Non-Slip Sole, Breathable Indoor Shoes with Cross Design, Perfect for All Seasons, Elegant Style",
        rating: "4.6 ⭐⭐⭐⭐",
        sold: "500 +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7"],
        colors: ["Pink", "Black", "Red", "Brown"]
    },
    {
        id: "8",
        image: "shoes/shoes8-1.webp",
        pics: "shoes/shoes8-1.webp,shoes/shoes8-2.webp,shoes/shoes8-3.webp,shoes/shoes8-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1829,
        oldPrice: 6790,
        discount: "-85%",
        description: " Women's Casual Slip-On Sneakers - Solid Color, Soft Fabric Lining, Non-Slip PU Sole for Fall",
        rating: "4.3 ⭐⭐⭐⭐⭐",
        sold: "5.7k +",
        sizes: ["3.5", "6.5", "7", "7.5", "8",],
        colors: ["Blue", "Brown", "Pink", "Green"]
    },
    {
        id: "9",
        image: "shoes/shoes9-1.webp",
        pics: "shoes/shoes9-1.webp,shoes/shoes9-2.webp,shoes/shoes9-3.webp,shoes/shoes9-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1942,
        oldPrice: 11554,
        discount: "-90%",
        description: " Women's Fashion Lightweight Sneakers, Breathable Mesh Lace Up Outdoor Shoes, Casual Comfortable Walking Shoes For Daily Wear",
        rating: "4.6 ⭐⭐⭐⭐⭐",
        sold: "2.9k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7", "7.5", "8",],
        colors: ["Brown", "Pink", "Green", "Grey"]
    },
    {
        id: "10",
        image: "shoes/shoes10-1.webp",
        pics: "shoes/shoes10-1.webp,shoes/shoes10-2.webp,shoes/shoes10-3.webp,shoes/shoes10-4.webp",
        category: "Women's Flats",
        title: "Flats ",
        price: 3172,
        oldPrice: 10891,
        discount: "-35%",
        description: "Chic Women's Ballet Flats with Bowknot - Comfortable Slip-On Shoes, Soft Sole, Versatile for All Seasons",
        rating: "4.1 ⭐⭐⭐⭐",
        sold: "1.5k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7", "7.5", "8",],
        colors: ["Black", "Pink", "LightPink", "OffWhite"]
    },
    {
        id: "11",
        image: "shoes/shoes11-1.webp",
        pics: "shoes/shoes11-1.webp,shoes/shoes11-2.webp,shoes/shoes11-3.webp,shoes/shoes11-4.webp,shoes/shoes11-5.webp,shoes/shoes11-6.webp,shoes/shoes11-7.webp",
        extraPics: "shoes/shoes11-1-extra.webp,shoes/shoes11-2-extra.webp,shoes/shoes11-3-extra.webp,shoes/shoes11-4-extra.webp,shoes/shoes11-5-extra.webp,shoes/shoes11-6-extra.webp,shoes/shoes11-7-extra.webp,shoes/shoes11-8-extra.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1766,
        oldPrice: 7039,
        discount: "-74%",
        description: "Women's Breathable Mesh Sneakers - Low Top, Fabric Lining, PVC Sole, Hand Washable - Versatile Sports Shoes for Walking, Tennis, Fitness, Gym - All-Season Comfort with Round Toe and Lace-Up Closure",
        rating: "4.9 ⭐⭐⭐⭐⭐",
        sold: "50k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5"],
        colors: ["Black(G-833)", "Blue (G-833)", "Brown (G-833)", "ColorfulBlue (G-833)", "Rose Red (G-833)", "Gray Pink (G-833)", "Gray (G-833)"]
    },
    {
        id: "12",
        image: "shoes/shoes12-1.webp",
        pics: "shoes/shoes12-1.webp,shoes/shoes12-2.webp,shoes/shoes12-3.webp",
        extraPics: "shoes/shoes12-1-extra.webp,shoes/shoes12-2-extra.webp,shoes/shoes12-3-extra.webp,shoes/shoes12-4-extra.webp,shoes/shoes12-5-extra.webp",
        category: "Women's Slide Sandals",
        title: "Women's Shoes",
        price: 4415,
        oldPrice: 15599,
        discount: "-71%",
        description: "[Durable Build] Elegant Women's Open-Toe Slide Sandals with Handcrafted Floral Rhinestone & Pearl Accents - Fashionable Beige Slip-On Flats, Perfect for All Seasons",
        rating: "4.8 ⭐⭐⭐⭐⭐",
        sold: "5.6k +",
        sizes: ["3.5", "4", "5", "6", "6.5", "6.5", "7", "7.5"],
        colors: ["Golden", "Rose Gold", "Black"]
    },
    {
        id: "13",
        image: "shoes/shoes13-1.webp",
        pics: "shoes/shoes13-1.webp,shoes/shoes13-2.webp,shoes/shoes13-3.webp,shoes/shoes13-4.webp,shoes/shoes13-5.webp",
        extraPics: "shoes/shoes13-1-extra.webp,shoes/shoes13-2-extra.webp,shoes/shoes13-3-extra.webp,shoes/shoes13-4-extra.webp",
        category: "Women's Wedge Sandals",
        title: "Women's Shoes",
        price: 2860,
        oldPrice: 9898,
        discount: "-71%",
        description: "Women's Rhinestone Decor Wedge Sandals, Casual Open Toe Platform Sandals, Comfortable Elastic Band Sandals",
        rating: "4.8 ⭐⭐⭐⭐⭐",
        sold: "5.6k ",
        sizes: ["3.5", "4", "5", "6", "6.5", "6.5", "7", "7.5"],
        colors: ["Sky Blue", "Silvery", "Dark Brown", "Rose Golden", "Rose Red"]
    },
    {
        id: "14",
        image: "shoes/shoes14-1.webp",
        pics: "shoes/shoes14-1.webp,shoes/shoes14-2.webp,shoes/shoes14-3.webp",
        extraPics: "shoes/shoes14-1-extra.webp,shoes/shoes14-2-extra.webp,shoes/shoes14-3-extra.webp,shoes/shoes14-4-extra.webp,shoes/shoes14-5-extra.webp",
        category: "Men's Sports & Outdoor Shoes",
        title: "Sports & Outdoors",
        price: 3006,
        oldPrice: 5380,
        discount: "-44%",
        description: "Men's Lace-Up Skate Sneakers - White with Blue & Red Stripe Design, Breathable PU Upper, Durable PVC Sole, Comfortable Casual Shoes for Casual Attire",
        rating: "4.9 ⭐⭐⭐⭐⭐",
        sold: "5.6k ",
        sizes: ["6.5", "7", "7.5", "8", "8.5", "9.5", "10", "11", "11.5"],
        colors: ["White & Black", "Black", "White & Grey"]
    },
    {
        id: "15",
        image: "shoes/shoes15-1.webp",
        pics: "shoes/shoes15-1.webp,shoes/shoes15-2.webp",
        extraPics: "shoes/shoes15-1-extra.webp,shoes/shoes15-2-extra.webp,shoes/shoes15-3-extra.webp,shoes/shoes15-4-extra.webp,shoes/shoes15-5-extra.webp,shoes/shoes15-6-extra.webp,shoes/shoes15-7-extra.webp,shoes/shoes15-8-extra.webp,shoes/shoes15-9-extra.webp",
        category: "Men's Casual Shoes",
        title: "Men's Shoes",
        price: 4272,
        oldPrice: 9281,
        discount: "-53%",
        description: "Men'S Casual Sneakers, Low Top, Fashionable Athletic Shoes, Faux, Fabric Lining, TPU Sole, Solid Color Design, Versatile Fit",
        rating: "5.0 ⭐⭐⭐⭐⭐",
        sold: "10k ",
        sizes: ["6", "6.5", "7", "7.5", "8.5", "9", "9.5", "10", "10.5", "11.5"],
        colors: ["Blue", "Green"]
    },
    {
        id: "16",
        image: "shoes/shoes16-1-extra.webp",
        pics: "shoes/shoes16-1.webp,shoes/shoes16-2.webp,shoes/shoes16-3.webp",
        extraPics: "shoes/shoes16-1-extra.webp,shoes/shoes16-2-extra.webp,shoes/shoes16-3-extra.webp,shoes/shoes16-4-extra.webp,shoes/shoes16-5-extra.webp,shoes/shoes16-6-extra.webp,shoes/shoes16-7-extra.webp,shoes/shoes16-8-extra.webp,shoes/shoes16-9-extra.webp",
        category: "Men's Casual Shoes",
        title: "Men's Shoes",
        price: 3760,
        oldPrice: 6743,
        discount: "-44%",
        description: "Men'S Stylish Sports Shoes, Casual Style, Breathable Lining, Durable, Suitable for Hiking And Outdoor Activities, Everyday Wear, Unisex.",
        rating: "4.6 ⭐⭐⭐⭐⭐",
        sold: "3.1k ",
        sizes: ["6", "6.5", "7", "8", "8.5", "9", "9.5", "10"],
        colors: ["Black", "Dark Brown" , "White"]
    },
    {
        id: "17",
        image: "shoes/shoes17-1.webp",
        pics: "shoes/shoes17-1.webp,shoes/shoes17-2.webp",
        extraPics: "shoes/shoes17-1.webp,shoes/shoes17-2.webp,shoes/shoes17-1-extra.webp,shoes/shoes17-2-extra.webp,shoes/shoes17-3-extra.webp",
        category: "Men's Casual Shoes",
        title: "Men's Shoes",
        price: 1844,
        oldPrice: 3871,
        discount: "-52%",
        description: "A Pair of Men'S Casual Sports Shoes for Spring And Autumn 2025, Breathable, Non-Slip, Stylish, And Versatile.",
        rating: "4.5 ⭐⭐⭐⭐⭐",
        sold: "1.8k ",
        sizes: ["5.5", "6.5", "7", "8", "8.5"],
        colors: ["Black", "White"]
    },
    {
        id: "18",
        image: "shoes/shoes18-1.webp",
        pics: "shoes/shoes18-1.webp,shoes/shoes18-2.webp",
        extraPics: "shoes/shoes18-1.webp,shoes/shoes18-2.webp,shoes/shoes18-1-extra.webp,shoes/shoes18-2-extra.webp,shoes/shoes18-3-extra.webp,shoes/shoes18-4-extra.webp,shoes/shoes18-5-extra.webp,shoes/shoes18-6-extra.webp",
        category: "Men's Semi-Formal Shoes",
        title: "Men's Shoes",
        price: 2663,
        oldPrice: 8098,
        discount: "-67%",
        description: "1 Pair Men'S Business Casual Shoes - Comfortable Fashion Sneakers, Non-Slip Durable Outdoor Footwear for Travel Party, All Seasons, Low Top Round Toe with Lace-Up Closure, Fabric Upper/Inner, PVC Sole.",
        rating: "4.7 ⭐⭐⭐⭐⭐",
        sold: "8.1k ",
        sizes: ["4", "5", "5.5", "6.5", "7" , "7.5", "8.5", "9.5", "10", "11"],
        colors: ["Blue", "Black"]
    },
    {
        id: "19",
        image: "shoes/shoes19-1.webp",
        pics: "shoes/shoes19-1.webp,shoes/shoes19-2.webp,shoes/shoes19-3.webp,shoes/shoes19-4.webp,shoes/shoes19-5.webp,shoes/shoes19-6.webp,shoes/shoes19-7.webp,shoes/shoes19-8.webp",
        extraPics: "shoes/shoes19-1-extra.webp,shoes/shoes19-2-extra.webp,shoes/shoes19-3-extra.webp,shoes/shoes19-4-extra.webp,shoes/shoes19-5-extra.webp",
        category: "Women's slippers",
        title: "Women's Shoes",
        price: 1172,
        oldPrice: 3544,
        discount: "-65%",
        description: "Women'S Two-Tone HOME Casual Open-Toe Comfortable Slippers for Home, Indoor, And Outdoor Use, Easy to Wear EVA Sandals.",
        rating: "4.7 ⭐⭐⭐⭐⭐",
        sold: "2.7k ",
        sizes: ["3.5-4", "4.5-5", "5.5-6", "6.5-7", "8.5-9"],
        colors: ["Dark Pink", "White", "Rose Red","Black", "Khaki", "Dark Grey","Dark Blue", "Bean Paste"]
    },
    {
        id: "20",
        image: "shoes/shoes20-2.webp",
        pics: "shoes/shoes20-1.webp,shoes/shoes20-2.webp,shoes/shoes20-3.webp,shoes/shoes20-4.webp",
        extraPics: "shoes/shoes20-1-extra.webp,shoes/shoes20-2-extra.webp,shoes/shoes20-3-extra.webp,shoes/shoes20-4-extra.webp,shoes/shoes20-5-extra.webp,shoes/shoes20-6-extra.webp,shoes/shoes20-7-extra.webp,shoes/shoes20-8-extra.webp",
        category: "Women's Flat Sandals",
        title: "Women's Shoes",
        price: 2011,
        oldPrice: 3872,
        discount: "-48%",
        description: "Women'S Bohemian Flat Sandals, Summer Casual Open Toe Slides with Toe Strap, Moire Pattern, All-Season Fabric Upper & Inner, Faux Sole, Buckle Closure - Fashionable Ladies Footwear.",
        rating: "4.7 ⭐⭐⭐⭐⭐",
        sold: "428",
        sizes: ["3.5", "4", "5", "5.5", "6.5","7", "7.5", "8.5"],
        colors: ["Multicolored", "Khaki", "Burgundy","Rose Red"]
    },
    {
        id: "21",
        image: "shoes/shoes21-1.webp",
        pics: "shoes/shoes21-1.webp,shoes/shoes21-2.webp,shoes/shoes21-3.webp,shoes/shoes21-4.webp,shoes/shoes21-5.webp,shoes/shoes21-6.webp,shoes/shoes21-7.webp,shoes/shoes21-8.webp",
        extraPics: "shoes/shoes21-1-extra.webp",
        category: "Women's Slide Sandals",
        title: "Women's Shoes",
        price: 767,
        oldPrice: 1324,
        discount: "-42%",
        description: "Women's Hollow Out Flat Slides, Solid Color Summer Outdoor Shoes, Minimalist Soft Sole Slides for Holidays.",
        rating: "4.7 ⭐⭐⭐⭐⭐",
        sold: "100k ",
        sizes: ["3.5-4", "4.5-5", "5.5-6", "7.5-8", "8.5-9"],
        colors: ["Black", "White", "lIGHT brown","Grey", "Pink", "Rose Red","Green"]
    },
    {
        id: "22",
        image: "shoes/shoes22-1.webp",
        pics: "shoes/shoes22-1.webp,shoes/shoes22-2.webp",
        extraPics: "shoes/shoes22-1-extra.webp,shoes/shoes22-2-extra.webp,shoes/shoes22-3-extra.webp,shoes/shoes22-4-extra.webp,shoes/shoes22-5-extra.webp,shoes/shoes22-6-extra.webp,shoes/shoes22-7-extra.webp",
        category: "Women's Flat Sandals",
        title: "Women's Shoes",
        price: 1331,
        oldPrice: 2219,
        discount: "-40%",
        description: "Women'S Elegant Floral Rose Platform Slides, Summer Round Toe Slip-On Beach Sandals with Ankle Strap, Non-Slip EVA Sole Comfort Wedge Shoes.",
        rating: "4.6 ⭐⭐⭐⭐⭐",
        sold: "984",
        sizes: ["2.5", "3", "3.5", "4", "4.5", "5.5", "6", "6.5"],
        colors: ["Red", "Blue"]
    },
    {
        id: "23",
        image: "shoes/shoes23-1.webp",
        pics: "shoes/shoes23-1.webp,shoes/shoes23-2.webp,shoes/shoes23-3.webp,shoes/shoes23-4.webp,shoes/shoes23-5.webp,shoes/shoes23-6.webp,shoes/shoes23-7.webp,shoes/shoes23-8.webp,shoes/shoes23-9.webp,shoes/shoes23-10.webp",
        extraPics: "shoes/shoes23-1-extra.webp,shoes/shoes23-2-extra.webp,shoes/shoes23-3-extra.webp,shoes/shoes23-4-extra.webp,shoes/shoes23-5-extra.webp,shoes/shoes23-6-extra.webp,shoes/shoes23-7-extra.webp", 
        category: "Women's Flat Sandals",
        title: "Women's Shoes",
        price: 1633,
        oldPrice: 5207,
        discount: "-68%",
        description: "Women's Fluffy Feather Slides, Solid Color Open Toe Single Band Flats, Casual Daily Slide Sandals",
        rating: "4.8 ⭐⭐⭐⭐⭐",
        sold: "984",
        sizes: ["3.5", "4", "5", "6", "6.5", "7.5", "8", "9"],
        colors: ["White", "Black", "Red", "Pink Red", "Green", "Light Purple", "Yellow", "Light Brown", "Mint Green", "Rose Red", ]
    },
]