let product = [
    {
        id: "1",
        image: "shoes/shoes1-1.webp",
        pics: "shoes/shoes1-1.webp,shoes/shoes1-2.webp,shoes/shoes1-3.webp,shoes/shoes1-4.webp",
        extraPics: "shoes/shoes1-1.webp,shoes/shoes1-2.webp,shoes/shoes1-3.webp,shoes/shoes1-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1730,
        oldPrice: 2500,
        discount: "20%",
        description: " Shoes Women's 2024 New Foreign Trade Women's Shoes Breathable Shoes Women's Cross-border Lace-up Fashion Trendy Sports Women's Shoes",
        rating: "⭐⭐⭐⭐",
        sold: "5k +",
        sizes: ["4", "4.5", "5", "6", "6.5", "7", "7.5", "8", ],
        colors: ["redOrange", "LightBrown", "NavyBlue", "Grey"]
    },
    {
        id: "2",
        image: "shoes/shoes2-1.webp",
        pics: "shoes/shoes2-1.webp,shoes/shoes2-2.webp,shoes/shoes2-3.webp,shoes/shoes2-4.webp",
        extraPics: "shoes/shoes2-1.webp,shoes/shoes2-2.webp,shoes/shoes2-3.webp,shoes/shoes2-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 3915,
        oldPrice: 5500,
        discount: "15%",
        description: "  Breathable Women's Slip-On Sneakers - Lightweight, Air Cushion Shock Absorption, Knit Upper,Casual Dance Shoes with Height Boost, All-Season Wear",
        rating: "⭐⭐⭐⭐⭐",
        sold: "2k +",
        sizes: ["4", "5", "6.5", "7",  "8", ],
        colors: ["Black", "Grey", "Purple", "Black&White"]
    },
    {
        id: "3",
        image: "shoes/shoes3-1.webp",
        pics: "shoes/shoes3-1.webp,shoes/shoes3-2.webp,shoes/shoes3-3.webp,shoes/shoes3-4.webp",
        extraPics: "shoes/shoes3-1.webp,shoes/shoes3-2.webp,shoes/shoes3-3.webp,shoes/shoes3-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1930,
        oldPrice: 3900,
        discount: "20%",
        description: "  Women's Solid Color Knitted Sneakers, Lace Up Soft Sole Lightweight Walking Shoes, Low-top Breathable Running Shoes",
        rating: "⭐⭐⭐⭐⭐",
        sold: "19k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7", "7.5", "8", ],
        colors: ["Black", "Red", "Pink", "White"]
    },
    {
        id: "4",
        image: "shoes/shoes4-1.webp",
        pics: "shoes/shoes4-1.webp,shoes/shoes4-2.webp,shoes/shoes4-3.webp,shoes/shoes4-4.webp",
        extraPics: "shoes/shoes4-1.webp,shoes/shoes4-2.webp,shoes/shoes4-3.webp,shoes/shoes4-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1570,
        oldPrice: 3267,
        discount: "50%",
        description: "Women's Breathable Camouflage Sports Sneakers, Low Top Lace-Up Fabric Shoes with EVA Sole and Rubber Patch, All-Season Plain Toe Design",
        rating: "⭐⭐⭐⭐",
        sold: "15k +",
        sizes: ["3.5", "4.5", "6.5", "7.5", ],
        colors: ["Pink", "Blue", "Brown", "Black"]
    },
    {
        id: "5",
        image: "shoes/shoes5-1.webp",
        pics: "shoes/shoes5-1.webp,shoes/shoes5-2.webp",
        extraPics: "shoes/shoes5-1.webp,shoes/shoes5-2.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 2700,
        oldPrice: 6200,
        discount: "65%",
        description: " Shoes Women's 2024 New Foreign Trade Women's Shoes Breathable Shoes Women's Cross-border Lace-up Fashion Trendy Sports Women's Shoes",
        rating: "⭐⭐⭐⭐⭐",
        sold: "35k +",
        sizes: ["3.5", "4", "4.5", "5", "6", ],
        colors: ["White", "Grey"]
    },
    {
        id: "6",
        image: "shoes/shoes6-1.webp",
        pics: "shoes/shoes6-1.webp,shoes/shoes6-2.webp,shoes/shoes6-3.webp,shoes/shoes6-4.webp",
        extraPics: "shoes/shoes6-1.webp,shoes/shoes6-2.webp,shoes/shoes6-3.webp,shoes/shoes6-4.webp",
        category: "Women's slippers",
        title: "slippers ",
        price: 945,
        oldPrice: 1200,
        discount: "25%",
        description: " Women's Comfy EVA Slides - Thick Sole, Non-Slip, Casual Slip-On Slippers in Pink, Green, Brown with Ribbed Texture - Perfect for Indoor/Outdoor Use, Beach & Home Relaxation, Ladies Slippers",
        rating: "⭐⭐⭐⭐",
        sold: "11k + ",
        sizes: ["6.5", "7", "7.5", "8", ],
        colors: ["Pink", "Khaki", "Grey", "White"]
    },
    {
        id: "7",
        image: "shoes/shoes7-1.webp",
        pics: "shoes/shoes7-1.webp,shoes/shoes7-2.webp,shoes/shoes7-3.webp,shoes/shoes7-4.webp",
        extraPics: "shoes/shoes7-1.webp,shoes/shoes7-2.webp,shoes/shoes7-3.webp,shoes/shoes7-4.webp",
        category: "Women's slippers",
        title: "slippers ",
        price: 1024,
        oldPrice: 3564,
        discount: "75%",
        description: " Elegant Floral Linen Slippers for Women - Soft, Non-Slip Sole, Breathable Indoor Shoes with Cross Design, Perfect for All Seasons, Elegant Style",
        rating: "⭐⭐⭐⭐",
        sold: "500 +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7" ],
        colors: ["Pink", "Black", "Red", "Brown"]
    },
    {
        id: "8",
        image: "shoes/shoes8-1.webp",
        pics: "shoes/shoes8-1.webp,shoes/shoes8-2.webp,shoes/shoes8-3.webp,shoes/shoes8-4.webp",
        extraPics: "shoes/shoes8-1.webp,shoes/shoes8-2.webp,shoes/shoes8-3.webp,shoes/shoes8-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1829,
        oldPrice: 6790,
        discount: "85%",
        description: " Women's Casual Slip-On Sneakers - Solid Color, Soft Fabric Lining, Non-Slip PU Sole for Fall",
        rating: "⭐⭐⭐⭐⭐",
        sold: "5.7k +",
        sizes: ["3.5", "6.5", "7", "7.5", "8", ],
        colors: ["Blue", "Brown", "Pink", "Green"]
    },
    {
        id: "9",
        image: "shoes/shoes9-1.webp",
        pics: "shoes/shoes9-1.webp,shoes/shoes9-2.webp,shoes/shoes9-3.webp,shoes/shoes9-4.webp",
        extraPics: "shoes/shoes9-1.webp,shoes/shoes9-2.webp,shoes/shoes9-3.webp,shoes/shoes9-4.webp",
        category: "Women's Fashion Sneakers",
        title: "Sneakers ",
        price: 1942,
        oldPrice: 11554,
        discount: "90%",
        description: " Women's Fashion Lightweight Sneakers, Breathable Mesh Lace Up Outdoor Shoes, Casual Comfortable Walking Shoes For Daily Wear",
        rating: "⭐⭐⭐⭐⭐",
        sold: "2.9k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7", "7.5", "8", ],
        colors: ["Brown", "Pink", "Green", "Grey"]
    },
    {
        id: "10",
        image: "shoes/shoes10-1.webp",
        pics: "shoes/shoes10-1.webp,shoes/shoes10-2.webp,shoes/shoes10-3.webp,shoes/shoes10-4.webp",
        extraPics: "shoes/shoes10-1.webp,shoes/shoes10-2.webp,shoes/shoes10-3.webp,shoes/shoes10-4.webp",
        category: "Women's Flats",
        title: "Flats ",
        price: 3172,
        oldPrice: 10891,
        discount: "35%",
        description: "Chic Women's Ballet Flats with Bowknot - Comfortable Slip-On Shoes, Soft Sole, Versatile for All Seasons",
        rating: "⭐⭐⭐⭐",
        sold: "1.5k +",
        sizes: ["3.5", "4", "4.5", "5", "6", "6.5", "7", "7.5", "8", ],
        colors: ["Black", "Pink", "LightPink", "OffWhite"]
    },
    {
    id: "11",
    image: "shoes/shoes11-1.webp",
    pics: "shoes/shoes11-1.webp,shoes/shoes11-2.webp,shoes/shoes11-3.webp,shoes/shoes11-4.webp,shoes/shoes11-5.webp,shoes/shoes11-6.webp,shoes/shoes11-7.webp",
    extraPics: "shoes/shoes11-1-extra.webp,shoes/shoes11-2-extra.webp,shoes/shoes11-3-extra.webp,shoes/shoes11-4-extra.webp,shoes/shoes11-5-extra.webp,shoes/shoes11-6-extra.webp,shoes/shoes11-7-extra.webp,shoes/shoes11-8-extra.webp,shoes/shoes11-1.webp,shoes/shoes11-2.webp,shoes/shoes11-3.webp,shoes/shoes11-4.webp,shoes/shoes11-5.webp,shoes/shoes11-6.webp,shoes/shoes11-7.webp",
    category: "Women's Fashion Sneakers",
    title: "Sneakers ",
    price: 1766,
    oldPrice: 7039,
    discount: "74%",
    description: "Women's Breathable Mesh Sneakers - Low Top, Fabric Lining, PVC Sole, Hand Washable - Versatile Sports Shoes for Walking, Tennis, Fitness, Gym - All-Season Comfort with Round Toe and Lace-Up Closure",
    rating: "⭐⭐⭐⭐⭐",
    sold: "50k +",
    sizes: ["3.5", "4", "4.5", "5", "6", "6.5"],
    colors: ["Black (G-833)", "Blue (G-833)", "Brown (G-833)", "ColorfulBlue (G-833)", "Rose Red (G-833)", "Gray Pink (G-833)", "Gray (G-833)"]
    }
]